// Electron main process — generated by kinetik init
const { app, BrowserWindow, screen, ipcMain, dialog } = require('electron');
const path = require('path');
const fs   = require('fs');

// ── Directories ─────────────────────────────────────────────────────────────
const levelsDir        = path.join(__dirname, 'levels');
const editorModelsDir  = path.join(__dirname, 'models', 'editor');
const editorActorsDir  = path.join(__dirname, 'models', 'actors');
const editorImagesDir  = path.join(__dirname, 'models', 'images');
const texturesDir      = path.join(__dirname, 'textures');
const soundsDir        = path.join(__dirname, 'sounds');

function getUserDataDir() {
  return app.getPath('userData');
}
const savesDir    = path.join(getUserDataDir(), 'saves');
const settingsDir = path.join(getUserDataDir(), 'settings');

[levelsDir, savesDir, editorModelsDir, editorActorsDir, editorImagesDir, texturesDir, soundsDir, settingsDir].forEach(d => {
  try { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); } catch { /* read-only asar */ }
});

let mainWindow;

function createWindow() {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;
  const isEditorMode = process.argv.includes('--editor');

  mainWindow = new BrowserWindow({
    width, height,
    frame: isEditorMode,
    fullscreen: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      webgl: true,
      preload: path.join(__dirname, 'preload.js'),
    },
    backgroundColor: '#12121e',
    show: false,
  });

  if (!isEditorMode) mainWindow.setPosition(0, 0);

  const isDev = !app.isPackaged;
  if (isDev) {
    if (isEditorMode) {
      mainWindow.loadFile('src/editor.html');
    } else {
      mainWindow.loadFile('src/index.html');
    }
  } else {
    mainWindow.loadFile(path.join(__dirname, 'src', isEditorMode ? 'editor.html' : 'index.html'));
  }

  mainWindow.once('ready-to-show', () => mainWindow.show());
  mainWindow.webContents.on('render-process-gone', (_, d) => {
    console.error('[CRASH] Renderer gone:', d.reason, d.exitCode);
  });
  mainWindow.on('closed', () => { mainWindow = null; });
}

app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });

ipcMain.on('quit-app', () => app.quit());

// ── Level management ─────────────────────────────────────────────────────────

ipcMain.handle('save-level', (_, { name, data }) => {
  const safe = name.replace(/[^a-zA-Z0-9_\-]/g, '_');
  fs.writeFileSync(path.join(levelsDir, safe + '.json'), JSON.stringify(data, null, 2), 'utf-8');
  return { ok: true };
});

ipcMain.handle('list-levels', () => {
  if (!fs.existsSync(levelsDir)) return [];
  return fs.readdirSync(levelsDir).filter(f => f.endsWith('.json')).map(f => f.slice(0, -5));
});

ipcMain.handle('read-level', (_, name) => {
  const p = path.join(levelsDir, name + '.json');
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { return null; }
});

// ── Model import ─────────────────────────────────────────────────────────────

ipcMain.handle('import-model', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import 3D Model',
    filters: [{ name: '3D Models', extensions: ['glb', 'gltf', 'fbx', 'obj'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src  = result.filePaths[0];
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(editorModelsDir, name));

  if (/\.obj$/i.test(name)) {
    const objDir  = path.dirname(src);
    const objText = fs.readFileSync(src, 'utf8');
    const mtlRefs = [];
    for (const line of objText.split('\n')) {
      const m = line.trim().match(/^mtllib\s+(.+)$/);
      if (m) mtlRefs.push(m[1].trim());
    }
    for (const mtlFile of mtlRefs) {
      const mtlSrc = path.join(objDir, mtlFile);
      if (!fs.existsSync(mtlSrc)) continue;
      fs.copyFileSync(mtlSrc, path.join(editorModelsDir, path.basename(mtlFile)));
      const mtlText = fs.readFileSync(mtlSrc, 'utf8');
      for (const line of mtlText.split('\n')) {
        const tm = line.trim().match(/^(?:map_[A-Za-z_]+|bump|norm|disp|refl)\s+(?:-\S+\s+)*(.+)$/i);
        if (!tm) continue;
        const texSrc = path.join(objDir, tm[1].trim());
        if (!fs.existsSync(texSrc)) continue;
        fs.copyFileSync(texSrc, path.join(editorModelsDir, path.basename(texSrc)));
      }
    }
  }

  return 'models/editor/' + name;
});

ipcMain.handle('list-models', () => {
  if (!fs.existsSync(editorModelsDir)) return [];
  return fs.readdirSync(editorModelsDir)
    .filter(f => /\.(glb|gltf|fbx|obj)$/i.test(f))
    .map(f => ({ name: f, path: 'models/editor/' + f }));
});

ipcMain.handle('import-image-model', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import Image Model',
    filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'webp'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src  = result.filePaths[0];
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(editorImagesDir, name));
  return 'models/images/' + name;
});

ipcMain.handle('list-image-models', () => {
  if (!fs.existsSync(editorImagesDir)) return [];
  return fs.readdirSync(editorImagesDir)
    .filter(f => /\.(png|jpg|jpeg|webp)$/i.test(f))
    .map(f => ({ name: f, path: 'models/images/' + f }));
});

// ── Actor import ─────────────────────────────────────────────────────────────

ipcMain.handle('import-actor', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import Actor Model',
    filters: [{ name: '3D Models', extensions: ['glb', 'gltf', 'fbx'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src  = result.filePaths[0];
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(editorActorsDir, name));
  return 'models/actors/' + name;
});

ipcMain.handle('list-actors', () => {
  if (!fs.existsSync(editorActorsDir)) return [];
  return fs.readdirSync(editorActorsDir)
    .filter(f => /\.(glb|gltf|fbx)$/i.test(f))
    .map(f => ({ name: f, path: 'models/actors/' + f }));
});

ipcMain.handle('import-actor-anim', async (_, actorPath) => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import Animation',
    filters: [{ name: '3D Models / Animations', extensions: ['glb', 'gltf', 'fbx'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src       = result.filePaths[0];
  const actorBase = path.basename(actorPath, path.extname(actorPath));
  const animsDir  = path.join(editorActorsDir, actorBase + '_anims');
  if (!fs.existsSync(animsDir)) fs.mkdirSync(animsDir, { recursive: true });
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(animsDir, name));
  return 'models/actors/' + actorBase + '_anims/' + name;
});

ipcMain.handle('list-actor-anims', (_, actorPath) => {
  const actorBase = path.basename(actorPath, path.extname(actorPath));
  const animsDir  = path.join(editorActorsDir, actorBase + '_anims');
  if (!fs.existsSync(animsDir)) return [];
  return fs.readdirSync(animsDir)
    .filter(f => /\.(glb|gltf|fbx)$/i.test(f))
    .map(f => ({ name: path.basename(f, path.extname(f)), file: 'models/actors/' + actorBase + '_anims/' + f }));
});

// ── Textures ─────────────────────────────────────────────────────────────────

ipcMain.handle('list-textures', () => {
  if (!fs.existsSync(texturesDir)) return [];
  return fs.readdirSync(texturesDir)
    .filter(f => /\.(png|jpg|jpeg|webp)$/i.test(f))
    .map(f => f.replace(/\.[^.]+$/, ''));
});

ipcMain.handle('import-texture', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import Texture',
    filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'webp'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src  = result.filePaths[0];
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(texturesDir, name));
  return name.replace(/\.[^.]+$/, '');
});

// ── Sounds ────────────────────────────────────────────────────────────────────

ipcMain.handle('list-sounds', () => {
  if (!fs.existsSync(soundsDir)) return [];
  return fs.readdirSync(soundsDir)
    .filter(f => /\.(mp3|ogg|wav|flac|m4a|aac)$/i.test(f))
    .map(f => f.replace(/\.[^.]+$/, ''));
});

ipcMain.handle('import-sound', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: 'Import Sound',
    filters: [{ name: 'Audio', extensions: ['mp3', 'ogg', 'wav', 'flac', 'm4a', 'aac'] }],
    properties: ['openFile'],
  });
  if (result.canceled || !result.filePaths.length) return null;
  const src  = result.filePaths[0];
  const name = path.basename(src);
  fs.copyFileSync(src, path.join(soundsDir, name));
  return name.replace(/\.[^.]+$/, '');
});

// ── Saves ─────────────────────────────────────────────────────────────────────

ipcMain.handle('write-save', (_, { slotKey, data }) => {
  const safe = slotKey.replace(/[^a-zA-Z0-9_\-]/g, '_');
  fs.writeFileSync(path.join(savesDir, safe + '.json'), JSON.stringify(data, null, 2), 'utf-8');
  return { ok: true };
});

ipcMain.handle('read-save', (_, slotKey) => {
  const safe = slotKey.replace(/[^a-zA-Z0-9_\-]/g, '_');
  const p = path.join(savesDir, safe + '.json');
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { return null; }
});

ipcMain.handle('list-saves', () => {
  if (!fs.existsSync(savesDir)) return [];
  return fs.readdirSync(savesDir).filter(f => f.endsWith('.json')).map(f => f.slice(0, -5));
});

ipcMain.handle('delete-save', (_, slotKey) => {
  const safe = slotKey.replace(/[^a-zA-Z0-9_\-]/g, '_');
  const p = path.join(savesDir, safe + '.json');
  if (fs.existsSync(p)) fs.unlinkSync(p);
  return { ok: true };
});

// ── Settings ──────────────────────────────────────────────────────────────────

ipcMain.handle('write-setting', (_, { key, value }) => {
  const safe = key.replace(/[^a-zA-Z0-9_\-]/g, '_');
  if (!fs.existsSync(settingsDir)) fs.mkdirSync(settingsDir, { recursive: true });
  fs.writeFileSync(path.join(settingsDir, safe + '.json'), JSON.stringify(value, null, 2), 'utf-8');
  return { ok: true };
});

ipcMain.handle('read-setting', (_, key) => {
  const safe = key.replace(/[^a-zA-Z0-9_\-]/g, '_');
  const p = path.join(settingsDir, safe + '.json');
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { return null; }
});

// ── GLB export ─────────────────────────────────────────────────────────────────

ipcMain.handle('save-glb', async (_, { defaultName, buffer }) => {
  const result = await dialog.showSaveDialog(mainWindow, {
    title: 'Export GLB',
    defaultPath: defaultName,
    filters: [{ name: 'GL Binary', extensions: ['glb'] }],
  });
  if (result.canceled || !result.filePath) return { ok: false };
  fs.writeFileSync(result.filePath, Buffer.from(buffer));
  return { ok: true, filePath: result.filePath };
});
