// preload.js — generated by kinetik init
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  quit:         () => ipcRenderer.send('quit-app'),

  saveLevel:    (name, data) => ipcRenderer.invoke('save-level', { name, data }),
  listLevels:   ()           => ipcRenderer.invoke('list-levels'),
  readLevel:    (name)       => ipcRenderer.invoke('read-level', name),

  importModel:      ()           => ipcRenderer.invoke('import-model'),
  listModels:       ()           => ipcRenderer.invoke('list-models'),

  importImageModel: ()           => ipcRenderer.invoke('import-image-model'),
  listImageModels:  ()           => ipcRenderer.invoke('list-image-models'),

  importActor:      ()            => ipcRenderer.invoke('import-actor'),
  listActors:       ()            => ipcRenderer.invoke('list-actors'),
  importActorAnim:  (actorPath)   => ipcRenderer.invoke('import-actor-anim', actorPath),
  listActorAnims:   (actorPath)   => ipcRenderer.invoke('list-actor-anims', actorPath),

  listTextures:   ()           => ipcRenderer.invoke('list-textures'),
  importTexture:  ()           => ipcRenderer.invoke('import-texture'),

  listSounds:     ()           => ipcRenderer.invoke('list-sounds'),
  importSound:    ()           => ipcRenderer.invoke('import-sound'),

  writeSave:    (slotKey, data) => ipcRenderer.invoke('write-save', { slotKey, data }),
  readSave:     (slotKey)       => ipcRenderer.invoke('read-save', slotKey),
  listSaves:    ()              => ipcRenderer.invoke('list-saves'),
  deleteSave:   (slotKey)       => ipcRenderer.invoke('delete-save', slotKey),

  writeSetting: (key, value) => ipcRenderer.invoke('write-setting', { key, value }),
  readSetting:  (key)        => ipcRenderer.invoke('read-setting', key),

  saveGlb: (defaultName, buffer) => ipcRenderer.invoke('save-glb', { defaultName, buffer }),
});
